/* eslint-disable */

//auto flag tell if the map should be considered when autoselecting the map
//places helps match the map with the data (without loading the map).  Names in here includes both region names (used with choropleth map) and landmark names (used with bubble markes)
//  that array can be quickly generated from the map file with (ajax used - must be run via webserver): map/getlandmarks.html#europe.json 

(function() {
  tdgchart.prototype.mapLibrary = [
    { auto: 0, file: "worldhq",  "domain": [ {"lng": -180, "lat": -59 }, {"lng": 180, "lat": 84} ] },
    { auto: 0, file: "world",    "domain": [ {"lng": -180, "lat": -56 }, {"lng": 180, "lat": 84} ] },
    { auto: 1, file: "us",       "domain": [ {"lng": -127, "lat": 24}, {"lng": -66, "lat": 50} ],   places: ["Alabama", "Arizona", "Arkansas", "Atlanta", "Augusta", "Austin", "Baton Rouge", "Bismarck", "Boise", "Boston", "California", "Charleston", "Cheyenne", "Chicago", "Colorado", "Columbia", "Connecticut", "Dallas", "Delaware", "Denver", "Des Moines", "Detroit", "Florida", "Georgia", "Helena", "Houston", "Idaho", "Illinois", "Indiana", "Indianapolis", "Iowa", "Jackson", "Kansas", "Kentucky", "Los Angeles", "Louisiana", "Maine", "Maryland", "Massachusetts", "Miami", "Michigan", "Minneapolis", "Minnesota", "Mississippi", "Missouri", "Montana", "Montgomery", "Nashville", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New Orleans", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oklahoma City", "Olympia", "Oregon", "Pennsylvania", "Philadelphia", "Phoenix", "Pierre", "Raleigh", "Rhode Island", "Richmond", "Sacramento", "Salem", "Salt Lake City", "San Diego", "San Francisco", "Santa Fe", "Seattle", "South Carolina", "South Dakota", "St. Louis", "St. Paul", "Tallahassee", "Tampa", "Tennessee", "Texas", "Topeka", "Utah", "Vermont", "Virginia", "Washington", "Washington, D.C.", "West Virginia", "Wisconsin", "Wyoming"] },
    { auto: 1, file: "usall",    "domain": [ {"lng": -125, "lat": 21 }, {"lng": -66, "lat": 50} ],  places: ["Alabama", "Alaska", "Anchorage", "Arizona", "Arkansas", "Atlanta", "Augusta", "Austin", "Baton Rouge", "Bismarck", "Boise", "Boston", "California", "Charleston", "Cheyenne", "Chicago", "Colorado", "Columbia", "Connecticut", "Dallas", "Delaware", "Denver", "Des Moines", "Detroit", "Florida", "Georgia", "Hawaii", "Helena", "Honolulu", "Houston", "Idaho", "Illinois", "Indiana", "Indianapolis", "Iowa", "Jackson", "Juneau", "Kansas", "Kentucky", "Los Angeles", "Louisiana", "Maine", "Maryland", "Massachusetts", "Miami", "Michigan", "Minneapolis", "Minnesota", "Mississippi", "Missouri", "Montana", "Montgomery", "Nashville", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New Orleans", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oklahoma City", "Olympia", "Oregon", "Pennsylvania", "Philadelphia", "Phoenix", "Pierre", "Raleigh", "Rhode Island", "Richmond", "Sacramento", "Salem", "Salt Lake City", "San Diego", "San Francisco", "Santa Fe", "Seattle", "South Carolina", "South Dakota", "St. Louis", "St. Paul", "Tallahassee", "Tampa", "Tennessee", "Texas", "Topeka", "Utah", "Vermont", "Virginia", "Washington", "Washington, D.C.", "West Virginia", "Wisconsin", "Wyoming"] },
    { auto: 1, file: "canada",   "domain": [ {"lng": -142, "lat": 41 }, {"lng": -52, "lat": 84} ],  places: ["Alberta", "Arctic Bay", "British Columbia", "Calgary", "Charlottetown", "Churchill", "Edmonton", "Fort Good Hope", "Fort Severn", "Halifax", "Manitoba", "Montr\u00e9al", "Nain", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Ottawa", "Prince Edward Island", "Prince Rupert", "Quebec", "Qu\u00e9bec", "Regina", "Repulse Bay", "Resolute", "Saskatchewan", "Saskatoon", "St. John", "St. John's", "Thunder Bay", "Toronto", "Vancouver", "Victoria", "Whitehorse", "Winnipeg", "Yellowknife", "Yukon"] }, 
    { auto: 1, file: "europe",   "domain": [ {"lng": -10, "lat": 34.5}, {"lng": 35, "lat": 71.5} ], places: ["Aland", "Albania", "Amsterdam", "Andorra", "Ankara", "Armenia", "Athens", "Austria", "Azerbaijan", "Barcelona", "Belarus", "Belgium", "Belgrade", "Berlin", "Bern", "Bosnia and Herz.", "Bratislava", "Brussels", "Bucharest", "Budapest", "Bulgaria", "Chisinau", "Croatia", "Cyprus", "Czech Rep.", "Dakar", "Denmark", "Dublin", "Estonia", "Faeroe Is.", "Finland", "France", "Frankfurt", "Geneva", "Georgia", "Germany", "Greece", "Guernsey", "Hamburg", "Helsinki", "Hungary", "Iceland", "Ireland", "Isle of Man", "Istanbul", "Italy", "Jersey", "Kazakhstan", "Kiev", "Kosovo", "K\u00f8benhavn", "Latvia", "Liechtenstein", "Lisbon", "Lithuania", "Ljubljana", "London", "Luxembourg", "Macedonia", "Madrid", "Malta", "Milan", "Minsk", "Moldova", "Monaco", "Montenegro", "Moscow", "Munich", "N. Cyprus", "Naples", "Netherlands", "Nicosia", "Norway", "Oslo", "Paris", "Podgorica", "Poland", "Portugal", "Prague", "Riga", "Romania", "Rome", "Russia", "San Marino", "Sarajevo", "Serbia", "Skopje", "Slovakia", "Slovenia", "Sofia", "Spain", "St. Petersburg", "Stockholm", "Sweden", "Switzerland", "Tallinn", "The Hague", "Tirana", "Turkey", "Ukraine", "United Kingdom", "Vaduz", "Valletta", "Vatican", "Vatican City", "Vienna", "Vilnius", "Warsaw", "Zagreb", "Zurich", "Z\u00fcrich"] },
    { auto: 1, file: "northamerica", "domain": [ {"lng": -172, "lat": 7 }, {"lng": -12, "lat": 84} ], places: ["Antigua and Barbuda", "Bahamas", "Barbados", "Belize", "Canada", "Costa Rica", "Cuba", "Dominica", "Dominican Republic", "El Salvador", "Grenada", "Guatemala", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Puerto Rico", "St. Kitts and Nevis", "St. Lucia", "St. Vincent and the Grenadines", "Trinidad and Tobago", "United States"] }
    //no entries for US states divided by county
    //no entries for US states divided by ZIP code
  ];
})();
